//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ltw.rc
//
#define DLG_LTW                         101
#define IDI_ICON1                       102
#define ICO_LTW                         102
#define BMP_CHN                         103
#define BMP_ENG                         104
#define BMP_FTHZ                        105
#define BMP_ACCURATE                    106
#define BMP_INTELI                      107
#define BMP_TRACE                       108
#define BMP_TRAN                        109
#define BMP_QUIT                        110
#define BMP_LEX                         111
#define IDC_ENGLISH                     1000
#define IDC_TRACE                       1001
#define IDC_FTHZ                        1002
#define IDC_CASE                        1003
#define IDC_AUTO                        1004
#define IDC_LIST                        1005
#define IDC_TRAN                        1006
#define IDC_EXIT                        1007
#define IDC_TEST                        1008
#define IDC_LEX                         1008
#define IDC_ABOUT                       1009
#define IDC_SAVE                        1010

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        112
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1011
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
